# Site settings
title: Bienvenido a mi blog!
description: Proyecto Final para la Licenciatura en Diseño de Videojuegos, SAE Institute México
cover: assets/images/cover.png
logo: assets/images/logo.png
favicon: assets/images/favicon.png
baseurl: "/blog/" # the subpath of your site, e.g. /blog/ or / for root
url: "https://polyirbis.github.io/" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

# Social
facebook: ShaunLeopard
twitter: polyirbis
github:  polyirbis

#Additional Pages
about: about
contact: contact


permalink: /:title


# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

plugins:
  - jekyll-paginate


# Settings for rake task
safe: False
lsi: False
username: polyirbis #github username
repo: polyirbis.github.io #github repository
branch: master #branch
relative_source: ../blog/ #source directory
destination: ../blog-pages/ #destination directory
production_url:  https://polyirbis.github.io/
source_url:  https://github.com/polyirbis/polyirbis.github.io/ #source repository url

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
